"""Georgian and English text displayed by the Desktop interface."""

from __future__ import annotations

from typing import Any


LANGUAGE_LABELS = {"ქართული": "ka", "English": "en"}
MODE_LABELS = {
    "ka": {
        "ავტომატური — რეკომენდებული": "Auto",
        "სწრაფი — მხოლოდ ტექსტი": "Fast",
        "სრული პაკეტი — OCR-ის გარეშე": "Full",
        "OCR — სკანირებული PDF": "Ocr",
    },
    "en": {
        "Automatic — recommended": "Auto",
        "Fast — text only": "Fast",
        "Full package — without OCR": "Full",
        "OCR — scanned PDF": "Ocr",
    },
}
EXCEL_MODE_LABELS = {
    "ka": {
        "ორივე ხედი — რეკომენდებული": "Both",
        "Workbook — ზუსტი და მცირე": "Workbook",
        "AutoFit — მხოლოდ დამხმარე ხედი": "AutoFit",
    },
    "en": {
        "Both views — recommended": "Both",
        "Workbook — exact and compact": "Workbook",
        "AutoFit — helper view only": "AutoFit",
    },
}

TEXT = {
    "ka": {
        "subtitle": "ფაილების მომზადება AI-სთვის — მარტივად და ლოკალურად",
        "file.section": "1. აირჩიე ფაილი",
        "file.hint": "PDF, Excel, სურათი ან Office დოკუმენტი",
        "file.browse": "არჩევა…",
        "options.section": "2. აირჩიე დამუშავების რეჟიმი",
        "options.hint": "თუ არ ხარ დარწმუნებული, დატოვე რეკომენდებული მნიშვნელობები",
        "options.mode": "ძირითადი რეჟიმი",
        "options.excel": "Excel-ის ხედები",
        "options.columns": "AutoFit სვეტების ზღვარი",
        "action.hint": "3. გაუშვი და დაელოდე შედეგს",
        "action.start": "დამუშავების დაწყება",
        "action.cancel": "გაუქმება",
        "details.title": "მიმდინარეობა და დეტალები",
        "details.check": "გარემოს შემოწმება",
        "details.setup": "Setup / Repair",
        "result.open": "შედეგის გახსნა",
        "result.copy": "AI დავალების კოპირება",
        "result.local": "ყველა დამუშავება სრულდება შენს კომპიუტერზე",
        "environment.engine": "ძრავა",
        "status.ready": "ფაილის ასარჩევად მზადაა",
        "status.output_cancelled": "შენახვის ადგილის არჩევა გაუქმდა",
        "status.starting": "დავალება იწყება…",
        "status.success": "დამუშავება წარმატებით დასრულდა",
        "status.environment_success": "გარემოს მოქმედება წარმატებით დასრულდა",
        "status.cancelled": "დავალება გაუქმდა",
        "status.failed": "დამუშავება შეცდომით დასრულდა",
        "status.cancel_requested": "გაუქმების მოთხოვნა მიღებულია — მიმდინარე უსაფრთხო ეტაპს ველოდებით…",
        "status.prompt_copied": "AI-სთვის დავალების ტექსტი დაკოპირდა",
        "file.none": "ჯერ ფაილი არ არის არჩეული",
        "file.missing": "ფაილი ვერ მოიძებნა",
        "file.detected": "ამოცნობილია: {kind} • {name}",
        "kind.pdf": "PDF დოკუმენტი",
        "kind.excel": "Excel workbook",
        "kind.image": "სურათი — OCR",
        "kind.document": "დოკუმენტი / მონაცემთა ფაილი",
        "dialog.choose_file": "აირჩიე დასამუშავებელი ფაილი",
        "dialog.all_supported": "ყველა მხარდაჭერილი ფაილი",
        "dialog.images": "სურათები",
        "dialog.all_files": "ყველა ფაილი",
        "dialog.choose_output": "სად შეინახოს ContextPack-ის შედეგი?",
        "dialog.no_file.title": "ფაილი არ არის არჩეული",
        "dialog.no_file.body": "ჯერ აირჩიე დასამუშავებელი ფაილი.",
        "dialog.invalid.title": "არასწორი პარამეტრი",
        "dialog.invalid.body": "DPI და სვეტების ზღვარი უნდა იყოს მთელი რიცხვი.",
        "dialog.cannot_start": "დავალება ვერ იწყება",
        "dialog.no_excel.title": "Excel ვერ მოიძებნა",
        "dialog.no_excel.body": "სრული Excel პაკეტის ვიზუალური რენდერისთვის Microsoft Excel საჭიროა. გაუშვი Environment Check ან Setup / Repair.",
        "dialog.no_ocr.title": "OCR გარემო მზად არაა",
        "dialog.no_ocr.body": "OCR-ისთვის საჭირო კომპონენტი ან ენის მოდელი აკლია. გაუშვი Setup / Repair.",
        "dialog.setup.body": "ეს მოქმედება შეამოწმებს და საჭიროების შემთხვევაში დააინსტალირებს პროექტის დამოკიდებულებებს. გაგრძელდეს?",
        "dialog.busy.title": "დავალება მიმდინარეობს",
        "dialog.busy.body": "ჯერ მიმდინარე დავალების დასრულებას დაელოდე.",
        "dialog.launch_failed": "გაშვება ვერ მოხერხდა",
        "dialog.ready.title": "მზადაა",
        "dialog.ready.body": "ContextPack-ის შედეგი მზადაა.\n\n{path}",
        "dialog.error.title": "შეცდომა",
        "dialog.error.body": "დავალება ვერ დასრულდა. დეტალები იხილე ქვედა ჟურნალში.",
        "dialog.result_missing": "შედეგი ვერ მოიძებნა",
        "dialog.close.title": "დავალება ჯერ მიმდინარეობს",
        "dialog.close.body": "გაუქმდეს მიმდინარე დავალება და პროგრამა უსაფრთხო გაჩერების შემდეგ დაიხუროს?",
        "validation.file_missing": "არჩეული ფაილი აღარ არსებობს.",
        "validation.mode": "არჩეული რეჟიმი უცნობია.",
        "validation.dpi": "DPI უნდა იყოს 96-დან 300-მდე.",
        "validation.excel_mode": "Excel-ის ხედის რეჟიმი უცნობია.",
        "validation.columns": "AutoFit-ის სვეტების ზღვარი უნდა იყოს 10-დან 200-მდე.",
        "validation.ocr_scope": "OCR რეჟიმი გამოიყენება მხოლოდ PDF-სა და სურათებზე.",
        "validation.output_missing": "შენახვისთვის არჩეული საქაღალდე აღარ არსებობს.",
        "log.selected_file": "არჩეული ფაილი: {path}",
        "log.output": "შენახვის ადგილი: {path}",
        "log.mode": "რეჟიმი: {mode} | DPI: {dpi} | Excel: {excel}",
        "log.error": "შეცდომა: {message}",
        "log.cancelled": "დავალება უსაფრთხოდ გაუქმდა.",
        "log.cancel_requested": "Cancel მოთხოვნილია. მიმდინარე ოპერაცია უსაფრთხოდ დასრულდება და შემდეგ დავალება გაჩერდება.",
        "prompt.line1": "გაეცანი ContextPack-ის ამ შედეგს: {path}",
        "prompt.line2": "ჯერ წაიკითხე manifest.json და quality-report.md, შემდეგ გახსენი მხოლოდ დავალებისთვის საჭირო ფაილები.",
        "prompt.goal": "მიზანი: [აქ ჩაწერე რა უნდა გაკეთდეს]",
    },
    "en": {
        "subtitle": "Prepare files for AI — simply and locally",
        "file.section": "1. Choose a file",
        "file.hint": "PDF, Excel, image, or Office document",
        "file.browse": "Browse…",
        "options.section": "2. Choose a processing mode",
        "options.hint": "Keep the recommended settings unless you need something specific",
        "options.mode": "Main mode",
        "options.excel": "Excel views",
        "options.columns": "AutoFit column limit",
        "action.hint": "3. Start and wait for the result",
        "action.start": "Start processing",
        "action.cancel": "Cancel",
        "details.title": "Progress and details",
        "details.check": "Check environment",
        "details.setup": "Setup / Repair",
        "result.open": "Open result",
        "result.copy": "Copy AI task",
        "result.local": "All processing stays on your computer",
        "environment.engine": "Engine",
        "status.ready": "Ready to choose a file",
        "status.output_cancelled": "Output folder selection was cancelled",
        "status.starting": "Starting the job…",
        "status.success": "Processing completed successfully",
        "status.environment_success": "Environment action completed successfully",
        "status.cancelled": "Job cancelled",
        "status.failed": "Processing failed",
        "status.cancel_requested": "Cancellation requested — waiting for the current safe boundary…",
        "status.prompt_copied": "AI task text copied",
        "file.none": "No file selected yet",
        "file.missing": "File not found",
        "file.detected": "Detected: {kind} • {name}",
        "kind.pdf": "PDF document",
        "kind.excel": "Excel workbook",
        "kind.image": "Image — OCR",
        "kind.document": "Document / data file",
        "dialog.choose_file": "Choose a file to process",
        "dialog.all_supported": "All supported files",
        "dialog.images": "Images",
        "dialog.all_files": "All files",
        "dialog.choose_output": "Where should ContextPack save the result?",
        "dialog.no_file.title": "No file selected",
        "dialog.no_file.body": "Choose a file to process first.",
        "dialog.invalid.title": "Invalid setting",
        "dialog.invalid.body": "DPI and the column limit must be whole numbers.",
        "dialog.cannot_start": "Cannot start the job",
        "dialog.no_excel.title": "Excel not found",
        "dialog.no_excel.body": "Microsoft Excel is required to render the complete visual Excel package. Run Check environment or Setup / Repair.",
        "dialog.no_ocr.title": "OCR environment is not ready",
        "dialog.no_ocr.body": "An OCR component or language model is missing. Run Setup / Repair.",
        "dialog.setup.body": "This checks the project dependencies and installs anything missing. Continue?",
        "dialog.busy.title": "A job is running",
        "dialog.busy.body": "Wait for the current job to finish first.",
        "dialog.launch_failed": "Could not start",
        "dialog.ready.title": "Ready",
        "dialog.ready.body": "Your ContextPack result is ready.\n\n{path}",
        "dialog.error.title": "Error",
        "dialog.error.body": "The job could not be completed. See the log below for details.",
        "dialog.result_missing": "Result not found",
        "dialog.close.title": "A job is still running",
        "dialog.close.body": "Cancel the current job and close after it stops safely?",
        "validation.file_missing": "The selected file no longer exists.",
        "validation.mode": "The selected mode is unknown.",
        "validation.dpi": "DPI must be between 96 and 300.",
        "validation.excel_mode": "The Excel view mode is unknown.",
        "validation.columns": "The AutoFit column limit must be between 10 and 200.",
        "validation.ocr_scope": "OCR mode can only be used with PDFs and images.",
        "validation.output_missing": "The selected output folder no longer exists.",
        "log.selected_file": "Selected file: {path}",
        "log.output": "Output folder: {path}",
        "log.mode": "Mode: {mode} | DPI: {dpi} | Excel: {excel}",
        "log.error": "Error: {message}",
        "log.cancelled": "The job was cancelled safely.",
        "log.cancel_requested": "Cancellation requested. The current operation will finish safely, then the job will stop.",
        "prompt.line1": "Review this ContextPack result: {path}",
        "prompt.line2": "Read manifest.json and quality-report.md first, then open only the files needed for the task.",
        "prompt.goal": "Goal: [describe what should be done]",
    },
}

STATUS_TRANSLATIONS = {
    "Checking the environment...": {"ka": "გარემო მოწმდება…", "en": "Checking the environment…"},
    "Environment check passed.": {"ka": "გარემო გამართულია.", "en": "Environment check passed."},
    "Installing or repairing dependencies...": {"ka": "კომპონენტები ყენდება ან ახლდება…", "en": "Installing or repairing dependencies…"},
    "Verifying the environment...": {"ka": "გარემო საბოლოოდ მოწმდება…", "en": "Verifying the environment…"},
    "Setup and environment check completed.": {"ka": "Setup დასრულდა და გარემო გამართულია.", "en": "Setup and environment check completed."},
    "Validating options and preparing the job...": {"ka": "პარამეტრები მოწმდება და დავალება მზადდება…", "en": "Validating options and preparing the job…"},
    "ContextPack is processing the file...": {"ka": "ContextPack ფაილს ამუშავებს…", "en": "ContextPack is processing the file…"},
    "PDF inspection finished.": {"ka": "PDF-ის შემოწმება დასრულდა.", "en": "PDF inspection finished."},
    "Workbook data extracted.": {"ka": "Excel-ის მონაცემები ამოღებულია.", "en": "Workbook data extracted."},
    "Visual pages rendered.": {"ka": "ვიზუალური გვერდები შექმნილია.", "en": "Visual pages rendered."},
    "Package finalized.": {"ka": "პაკეტი საბოლოოდ შეიქმნა.", "en": "Package finalized."},
    "Output finalized.": {"ka": "შედეგი საბოლოოდ შეიქმნა.", "en": "Output finalized."},
    "The job completed successfully.": {"ka": "დამუშავება წარმატებით დასრულდა.", "en": "The job completed successfully."},
    "The job was cancelled safely.": {"ka": "დავალება უსაფრთხოდ გაუქმდა.", "en": "The job was cancelled safely."},
}


def translate(language: str, key: str, **values: Any) -> str:
    """Render a localized UI message, falling back to Georgian then English."""

    language = language if language in TEXT else "ka"
    template = TEXT[language].get(key, TEXT["en"].get(key, key))
    return template.format(**values)


def label_for_value(labels: dict[str, dict[str, str]], language: str, value: str) -> str:
    """Return the localized label associated with an internal option value."""

    return next(label for label, code in labels[language].items() if code == value)


def translate_runner_status(message: str, language: str) -> str:
    """Translate a stable status message emitted by the PowerShell runner."""

    return STATUS_TRANSLATIONS.get(message, {}).get(language, message)

